language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
    secure: FEvYbd0KCJX8RehO0pKV9bDJgo4vN73k3IbZ/ml840xP8Z5B4GsDIr2BjKcicrGbtycuL1d3VfEtDcCoQ2x3Y6xD8UVe/+s2CY+YCG4dGl+nZeU7FWn9+X0QQwRuUmKH0IKrZlGYKDLFrZPW4amMkPInpEivzFTUPr6tUY3pOyc=
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#annotator
    on_success: change
    on_failure: change
