language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  matrix:
    secure: BamO7vxCTFM6Doc1+S6Rc3oD+si7LjJtlsOp6YqHdCPW4yxBy7x8EHbcPHw8JVzKDnrGkH1KqwdDsWLVWJwix7FxiNRw6cs0VCQVCJrmqXdPOMBR6okNd3L6c1uRFd8rdM0cxfHd2FkJWQPIsL5ptCOxv6/MS4aWqn2u+lGVadA=
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#annotator
    on_success: change
    on_failure: change
